name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          repository: benz2012/wiggle-tools
          path: wiggle-tools
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: benz2012/wiggle-animate
          file: release.zip

      - name: Setup folders
        run: mkdir -p ./build/_subapps
      - name: Build Wiggle Tools
        run: |
          cd wiggle-tools
          npm ci
          npm run build
          cp -r ./public/. ../build/
      - name: Unzip pre-built Wiggle Animate
        run: |
          unzip release.zip -d wiggle-animate
          cp -r ./wiggle-animate/build/ ./build/_subapps/animate/
      - name: Report entire build folder
        run: find ./build/

      - run: cp ./wiggle-tools/firebase.json ./wiggle-tools/.firebaserc ./
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WIGGLE_TOOLS }}'
          channelId: live
          projectId: wiggle-tools
